### ISSUE TITLE
Links to tutorials not working

### ISSUE THREAD

**Issue by marlisese** [de-Boer-Lab/MAUDE#1]
Hi MAUDE coders, 
I wonder if the links to the tutorials could be updated, I am interested to test your method in FACS sorted CRISPR screens. 
Thanks, 
Martha

**Comment by Carldeboer** [comment]
Thanks for pointing this out! They should be fixed now. Please let us know if you encounter any other issues.

**Comment by marlisese** [comment]
Dear Carl, 
Thanks a lot for your fast response. I am going through the MAUDE publication [here](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02046-8) but is not fully clear to me whether your method would help in cases of pooled screens (~2k genes) and FACS sorted phenotypes [like this](https://www.biorxiv.org/content/10.1101/2021.05.11.443701v1) Thanks in advance. 
Martha

**Comment by Carldeboer** [comment]
Yes, it looks like that's an ideal use case. You just need some information that is not always readily available (e.g. bin sizes, sequencing of the "input" DNA). Though there are ways around these requirements. Please let me know in a new issue if you have any specific problems with these.
