### ISSUE TITLE
Maude for whole genome FACS screening

### ISSUE THREAD

**Issue by fulaibaowang** [de-Boer-Lab/MAUDE#6]
Hi,

I am wondering if MAUDE is designed for seeing the impact of guide RNAs on ONE target gene or if it also applies for whole genome FACS screening. In the tutorial it is all about one gene.

For whole genome FACS the input count table would be a bit different: there is no coordinates of a gene but different targetted genes. 

Many thanks!

**Comment by Carldeboer** [comment]
Sorry, can you explain what you mean by whole genome FACS screening?
A typical MAUDE use case would be something like a genome-wide CRISPR screen, where guides target each gene in the genome. Then, their effect on one particular target gene's expression is read out via FACS (e.g. by labeling that target gene). For instance, we want to know all the genes that regulate CD69, so we perform a CRISPR screen where each gene in the genome is deleted and then we sort cells by CD69 (e.g. via antibody staining) into high/low CD69 expression to find guides that are enriched in either high or low bins. Then we infer what genes regulate CD69 via the direct target of the CRISPR guides.
Does that help?

**Comment by fulaibaowang** [comment]
Thanks, very helpful! I mean if MAUDE is suitable for the analysis that the readout via FACS is not gene expression of one target gene but something else,  for example the GFP reconstitution.

**Comment by Carldeboer** [comment]
Yes, we have used it for GFP reporter assays too (e.g. Sort-seq). It works well there as well.  Anything with a FACS readout followed by sequencing entities within the sorting bins seems to work quite well.

**Comment by fulaibaowang** [comment]
Thanks a lot for the reply. Really appreicated. I was following your example on CD69 and could learn a lot. But this example was for one gene and there is genomic coordinates data available for the element level analysis. 

My question is then: for a GFP reporter assays for example to find out gene essentiality, which elements mean different genes, not genomic coordinates of one gene, which function in MAUDE will be suitable?

**Comment by Carldeboer** [comment]
Glad you figured it out! Yes, the elements can be arbitrary. They can be genes, regulatory regions, sequences, RNAs, etc.
